### ISSUE TITLE
[bug]: RPC ERROR: Database Error error returned from database: could not open file "base/16385/2601": Read-only file system

### ISSUE THREAD

**Issue by MKant0** [Start9Labs/start-os#2140]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Ventura 13.1

### Browser

Chrome

### Browser Version

109.0.5414.119 (Build oficial) (arm64)

### Current Behavior

Whenever I try to connect to my node the error appears, in Windows/MacOS in Chrome, Firefox and Tor. I tried rebutting the node by disconnecting it from the power source and when I plugged in the power connector I couldn't even access to the login page.

I tried reinstalling the OS and it worked. Later in the day my account logged off and I lost access again... back to the loop.

### Expected Behavior

to gain access to the OS.

### Steps to Reproduce

1. On this page http://embassy-amber-policy.local/#/login
2. introducing my password
3. Error appears.

**Comment by kn0wmad** [comment]
What hardware is this?

**Comment by MKant0** [comment]
It's a raspberry pi 4

**Comment by QooXyy** [comment]
Same problem worked fine yesterday. Also on a Raspberry Pi 4.

**Comment by BitcoinMechanic** [comment]
What SSDs and enclosures are you using?

**Comment by QooXyy** [comment]
> What SSDs and enclosures are you using?

I’m using a Samsung 870 QVO 1 TB and an ORICO Hard Drive Enclosure.

**Comment by MKant0** [comment]
I´m ussing this:

![image](https://user-images.githubusercontent.com/86203317/215511104-0c2bf775-86f9-4545-be6a-8981804908ca.png)

**Comment by kn0wmad** [comment]
> I´m ussing this:
> 
> ![image](https://user-images.githubusercontent.com/86203317/215511104-0c2bf775-86f9-4545-be6a-8981804908ca.png)

Unfortunately the JMicron devices are known to cause problems.  We are able to audit our own enclosures, but we no longer recommend them since they are made by different manufacturers, which makes them unreliable.  This is why we moved to an all-in-one case with proper power management and larger power supply.

Your problems are almost certainly with this hardware.  @QooXyy - you can find out if you have a JMicron device by running `lsusb` after plugging the enclosure into a Linux machine.

**Comment by QooXyy** [comment]
> > I´m ussing this:
> > ![image](https://user-images.githubusercontent.com/86203317/215511104-0c2bf775-86f9-4545-be6a-8981804908ca.png)
> 
> Unfortunately the JMicron devices are known to cause problems. We are able to audit our own enclosures, but we no longer recommend them since they are made by different manufacturers, which makes them unreliable. This is why we moved to an all-in-one case with proper power management and larger power supply.
> 
> Your problems are almost certainly with this hardware. @QooXyy - you can find out if you have a JMicron device by running `lsusb` after plugging the enclosure into a Linux machine.

Yeah I think it’s JMicron.

**Comment by gStart9** [comment]
> > > I´m ussing this:
> > > ![image](https://user-images.githubusercontent.com/86203317/215511104-0c2bf775-86f9-4545-be6a-8981804908ca.png)
> > 
> > 
> > Unfortunately the JMicron devices are known to cause problems. We are able to audit our own enclosures, but we no longer recommend them since they are made by different manufacturers, which makes them unreliable. This is why we moved to an all-in-one case with proper power management and larger power supply.
> > Your problems are almost certainly with this hardware. @QooXyy - you can find out if you have a JMicron device by running `lsusb` after plugging the enclosure into a Linux machine.
> 
> Yeah I think it’s JMicron. So just get a Geekworm NASPi V2.0 case and I’m good right?

Yes that should work.  If you want to follow our guide you will have the speaker helpful for diagnostics, better fan, etc:
https://docs.start9.com/latest/diy/diy-pi

**Comment by QooXyy** [comment]
> 

Well after getting the Case setting everything up again same error and after restart not finding server anymore. What now?

**Comment by kn0wmad** [comment]
> > 
> 
> Well after getting the Case setting everything up again same error kinda I think something with Database Error 2 it was. And after restart not finding server anymore. What now? Had umbrel installed before and everything worked fine there, but found embassy, and I like it much more.

We'll need more context to understand your problem.  How are you trying to access and what error are you getting?  Are you getting startup sounds from Embassy?  If so, which ones?

**Comment by QooXyy** [comment]
> > > 
> > 
> > 
> > Well after getting the Case setting everything up again same error kinda I think something with Database Error 2 it was. And after restart not finding server anymore. What now? Had umbrel installed before and everything worked fine there, but found embassy, and I like it much more.
> 
> We'll need more context to understand your problem. How are you trying to access and what error are you getting? Are you getting startup sounds from Embassy? If so, which ones?

Got no speaker on it everything worked till I rebooted then database error again after that page just offline even after reboot, Would love to give more info, but that's it basically it. Installed everything worked reboot -> database error -> just error with no info -> page offline

**Comment by MKant0** [comment]
There must be something wrong in your side, because its working in Umbrel...

![image](https://user-images.githubusercontent.com/86203317/216829044-a4106899-6b49-4c55-b3ac-048b0d276786.png)

**Comment by MKant0** [comment]
> 

There must be something wrong in your side, because Umbrel works well...

![image](https://user-images.githubusercontent.com/86203317/216829196-5d7a8bd9-5df7-4711-8fe1-a1654cdb5736.png)

**Comment by gStart9** [comment]
@MKant0 are you using the exact same hardware?  Like you formatted the disk and went back to umbrel?  Or what exactly?

Read-only file system can indicate errors detected on the filesystem, then it mounted it read only so that writes wouldn't further corrupt it.  Usually a few reboots will make the error go away but if it persists, a good way to proceed is probably to back up your data if possible and then start with a freshly wiped partitions and then fresh partitions with a freshly formatted filesystem.

**Comment by MKant0** [comment]
> @MKant0 are you using the exact same hardware?  Like you formatted the disk and went back to umbrel?  Or what exactly?
> 
> Read-only file system can indicate errors detected on the filesystem, then it mounted it read only so that writes wouldn't further corrupt it.  Usually a few reboots will make the error go away but if it persists, a good way to proceed is starting with wiping the partitions and then fresh partitions with a freshly formatted filesystem.

I'm ussing the same setup, no changes.

I rebooted embassy os 3 times, every time it worked great at the first login, after a couple of hours I couldn't access back by local and tor.

**Comment by gStart9** [comment]
"couldn't access" - meaning that's when you saw the errors about the read only filesystem?

**Comment by kn0wmad** [comment]
> > 
> 
> There must be something wrong in your side, because Umbrel works well...
> 
> ![image](https://user-images.githubusercontent.com/86203317/216829196-5d7a8bd9-5df7-4711-8fe1-a1654cdb5736.png)

If you search their support channels, you will find that "read-only" filesystem errors happen on umbrel, mynode, ronin dojo, and raspiblitz as well.  This is not a problem with embassyOS.  This problem is at the kernel level and from what we can gather it is due to the Raspberry Pi's inferior data connection combined with issues surrounding external enclosures/drives.  These machines were simply not built to deal with external storage and be used as servers, but the NASPi option we have built is generally reliable.  These issues are infrequent, and are almost always fixed by a reboot, which is suggested by all the projects I listed above.  There is another possible workaround, but due to risk of data corruption, we have decided not to implement it - if you search around you will find it, but we do not recommend it.  If you are not getting the same error, then there is a different problem and we are happy to help diagnose that.  If the error is the same, you may try re-seating the USB "loop" at the back of the device, or testing with a usb-to-usb cable as we have occasionally seen these arrive DOA.

**Comment by RhynoTech** [comment]
I have also recently been getting this error. My hardware is:

> Argon ONE M.2 case

> SanDisk 32GB MAX Endurance Micro SD

> WD Blue 2TB SSD

It seems that after rebooting everything works. Unfortuneately after some time passes I get logged out and upon trying to login again I get the same error.

**Comment by kn0wmad** [comment]
> I have also recently been getting this error. My hardware is:
> 
> > Argon ONE M.2 case
> 
> > SanDisk 32GB MAX Endurance Micro SD
> 
> > WD Blue 2TB SSD
> 
> It seems that after rebooting everything works. Unfortuneately after some time passes I get logged out and upon trying to login again I get the same error.
> 
> Edit: It seems to happen daily BTW

You might like to try a USB cable instead of the USB adapter on back - sometimes these can be poor quality.  If the cable works, then replace the adapter.

**Comment by RhynoTech** [comment]
Replacing the adapter with a USB cable seems to have done the trick. So far so good, thanks for the advice :)

![image](https://user-images.githubusercontent.com/50632955/230745332-788190a2-4edf-4874-963f-25fd60024d47.png)
