### ISSUE TITLE
[feat] Do Not Allow Downgrade to Progress When "Downgrades Prohibited"

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2174]
Currently when performing a downgrade migration, download is completed before error is thrown and migration is abandoned (with error).  It would be more ideal to tell the user as soon as they attempt the downgrade.

**Comment by chrisguida** [comment]
This would be a pretty big change. This would require us to run the migration before starting the download (since there would be no other way to know whether the migration will error). This would probably require us to implement migration rollbacks (which are probably desirable anyway).

The other option would be to specify a prohibited migration somewhere in the *manifest*, rather than in the migration js.

Are there any other possible ways to implement @dr-bonez ?
