### ISSUE TITLE
[bug]: electrs dependencies problem

### ISSUE THREAD

**Issue by AndySchroder** [Start9Labs/start-os#2321]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### StartOS Version

0.3.4.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

N/A

### Browser

Firefox

### Browser Version

N/A

### Current Behavior

I get a dependency error for electrs. It says it wants bitcoin core >=0.21.1.1<26.0.0 . Start9 has installed bitcoin core 24.0.1, so I don't know what the problem is.

### Expected Behavior

start9 should do dependency checks correctly and packages should only be distributed that match real dependency checks.

### Steps to Reproduce

1. install start9
2. install bitcoin core
3. install electrs

**Comment by MattDHill** [comment]
I can't imagine what could cause this. We have many thousands of people running these two services with no issue. Think you could provide a screenshot or some debugging information from the console. I would be happy to jump on a screen share to dig in as well.

**Comment by MattDHill** [comment]
What does the error say? Is Bitcoin actually running and healthy?

**Comment by MattDHill** [comment]
Perhaps the UI is not perfect, but that error is not saying there is a version compatibility issue. It clearly says the problem is Bitcoin is failing a health check. Electrs is unhappy and may not work as expected because Bitcoin is failing a health check. This is true and accurate. Electrs will not work as expected until Bitcoin's "synced" health check passes. Everything working as you suggest and as it should. Again, maybe a feature request to "hide" the version range of dependencies to avoid confusion.
