### ISSUE TITLE
[feat] Containerize StartOS

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2548]
Allow users to run StartOS as the base OS in a (docker) container.  Low priority, and not hugely demanded, but does open up some opportunities for developers, for example, [running in WSL](https://www.spatacoli.com/blog/2020/03/custom-wsl-image/).

**Comment by dr-bonez** [comment]
Given the limitations of running containers inside containers, this is not possible at this time. If the technology evolves such that becomes available, we can reopen this issue

**Comment by priuatus** [comment]
Docker is was designed for containerizing applications rather than whole distributions. Linux Containers (LXC) was designed specifically to containerize distributions and docker has no problem running inside an LXC container. It would be great if we could run StartOS in a Proxmox LXC container. Right now I'm testing StartOS inside a KVM VM, but that has more overhead and limits my options with regards to the storage backend. Also there is an exciting upcoming linux container/vm manager called Incus that is gaining a lot of adoption in the open source community.

Please consider reopening this issue specifying LXC as the container technology. I'm willing to contribute to the MR or the testing of the feature.

- [LXC](https://linuxcontainers.org/)
- [FOSDEM 2024: Introducing Incus](https://www.youtube.com/watch?v=ZdcQSmkF_4U)

**Comment by dr-bonez** [comment]
Given that start-os is [moving towards converting all of its existing containers to lxc containers](https://video.fosdem.org/2024/ub2252a/fosdem-2024-3063-using-chroots-in-a-single-linux-container-as-an-alternative-to-docker-compose.av1.webm), the same problem remains. While it is technically possible to run lxc inside lxc, the inner containers would have to run unconfined, and it is not clear we could obtain the necessary inter-service isolation that we expect for our security model.
