### ISSUE TITLE
[bug]: Cannot install Start-OS desktop, x.org error

### ISSUE THREAD

**Issue by techrivertree** [Start9Labs/start-os#2804]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Beelink RSO5 mini PC (Ryzen 7, 16GB DDR4)

### StartOS Version

0.3.5.1-39DEO98_X86_64

### Client OS

Linux

### Client OS Version

Ubuntu 22.04 LTS

### Browser

Firefox

### Browser Version

133.0.3

### Current Behavior

When trying to install, an error occurs, something about an x.org error.

### Expected Behavior

Start OS should install.

### Steps to Reproduce

1: Download ISO from here
2: Use SHA256 to verify download (first 7 downloads were corrupted...)
3: Use RPi imager to flash ISO  - Error: Unable to customize. File '/me/username/StartOS v0.3.5.1 amd64/config.txt' Does not exist.
4. Click continue.
5. Attempt to install - will fail due to some x.org error.

### Anything else?

Might be due the error with RPi imager, I search, I could not find anything related to StartOS.

**Comment by techrivertree** [comment]
![signal-2024-12-19-164209_002](https://github.com/user-attachments/assets/f31402e0-d2de-43c9-a1ce-0a9897c5e275)
![Screenshot from 2024-12-19 16-44-37](https://github.com/user-attachments/assets/83850bd5-010c-429f-a433-c43d9294fb26)

**Comment by stupleb** [comment]
Two initial comments...

1. I'm not sure or convinced that the Pi Imager is a good choice, while I may be entirely wrong and it may be more powerful that I know, the wording of "Unable to customize" makes me think that it's doing something more than it should, something specific perhaps for and ARM processor... which would make sense considering it's a imager for RPis. I would eliminate this as a vector for troubleshooting by just using Balena Etcher, as detailed in the flashing guides. You mention this yourself, so it's a good first step.

2. From the githash, it looks like you've got the nonfree image there, which is good. You definitely need the `x86_64-nonfree.iso`. At this stage, without looking into point 1 above, this might just be to do with a bad flashing with your chosen imager, since we don't even get as far as X failing for something like missing drivers. If bits of the OS are missing, or permission are wrong, this could explain `xauth file /home/kiosk/.xauthority does not exist`

**Comment by techrivertree** [comment]
I downloaded the nonfree iso and used balena etcher to flash the iso to my brand new sandisk USB thumb drive. Flash completed successfully. I was able to get the install wizard screen where I selected the 500GB NVME SSD to install StartOS on it. After installation was complete I was told to remove installation media and reboot. After rebooting, the same error occurred as with RPi imager.
![signal-2024-12-20-120821](https://github.com/user-attachments/assets/dbbd5123-b825-4800-b1cb-5c84bae29712)

**Comment by techrivertree** [comment]
It looks like the unbranded NVME SSD (Crucial P3) might be the problem. I installled a spare 1TB 2.5" SSD and everything installed correctly, if only it would show a log screen. More troubleshooting is needed but this bug can be closed.
